---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-diners-payment
  namespace: fiap-sa
  labels:
    app: fiap-diners-payment
  annotations:    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-diners-payment
  template:
    metadata:
      labels:
        app: fiap-diners-payment
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fiap-diners-payment
            topologyKey: kubernetes.io/hostname
      containers:
      - image: 891377307312.dkr.ecr.us-east-1.amazonaws.com/fiap-sa-api:latest # add updated image
        name: fiap-diners-payment
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 256Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: fiap-diners-payment-configmap
        - secretRef:
            name: fiap-diners-payment-secrets
        volumeMounts:
        - name: ephemeral
          mountPath: /tmp
      volumes:
      - name: ephemeral
        emptyDir: {}
      imagePullSecrets:
      - name: docker-registry
